<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-04-26">
<meta name="description" content="A team from Green Shield Canada explores Apache Parquet as an option for data processing. With the parquet file format, the team was able to process data 1,500 times faster than with CSVs.">

<title>Speed Up Data Analytics and Wrangling With Parquet Files</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
</style>


<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html.min.css" rel="stylesheet" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">


</head>

<body>


<header id="title-block-header">
<h1 class="title">Speed Up Data Analytics and Wrangling With Parquet Files</h1>

<p class="date">2022-04-26</p>
</header>

<p><sup>Photo by <a href="https://unsplash.com/@jakegivens?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jake Givens</a> on <a href="https://unsplash.com/s/photos/fast?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a> </sup></p>
<div class="lt-gray-box">
<p>This is a guest post from Ryan Garnett, Ray Wong, and Dan Reed from Green Shield Canada. <a href="https://www.greenshield.ca/en-ca/" target="_blank">Green Shield Canada</a>, a social enterprise and one of the country’s largest health benefits carriers, currently serves over 4.5 million Canadians across health and dental benefits and pharmacy benefits management. GSC also provides clients with an integrated experience that includes health care delivery via an ever-expanding digital health ecosystem and full benefits administration support.</p>
</div>
<p><link href="style.css" rel="stylesheet"></p>
<h2 id="the-challenge" class="anchored">The Challenge</h2>
<p>Data is increasing in value for many organizations — an asset leveraged to help make informed business decisions. Unfortunately, this sentiment has not been the norm throughout the life of most organizations, with vast amounts of data locked in legacy data management systems and designs. The majority of organizations use relational database management systems (RDBMS) like Oracle, Postgres, Microsoft SQL, or MySQL to store and manage their enterprise data. Typically these systems were designed to collect and process data quickly within a transactional data model. While these models are excellent for applications, they can pose challenges for performing business intelligence, data analytics, or predictive analysis. Many organizations are realizing their legacy systems are not sufficient for data analytics initiatives, providing an opportunity for analytics teams to present tangible options to improve their organization’s data analytics infrastructure.</p>
<p>Regardless if you are engineering data for others to consume for analysis, or performing the analytics, reducing the time to perform data processing is critically important. Within this post, we are going to evaluate the performance of two distinct data storage formats; row-based (CSV) and columnar (parquet); with CSV being a tried and tested standard data format used within the data analytics field, and parquet becoming a viable alternative in many data platforms.</p>
<h2 id="setup" class="anchored">Setup</h2>
<p>We performed the analysis for the post on Green Shield Canada’s analytics workstation. Our workstation is a shared resource for our analytics team that is running RStudio Workbench with the following configurations:</p>

<table>
<tbody>
<tr class="odd">
<td>
<em>Operating system</em>
</td>
<td>
Ubuntu 20
</td>
</tr>
<tr class="even">
<td>
<em>Cores</em>
</td>
<td>
16
</td>
</tr>
<tr class="odd">
<td>
<em>CPU speed</em>
</td>
<td>
2.30GHz
</td>
</tr>
<tr class="even">
<td>
<em>RAM</em>
</td>
<td>
1TB
</td>
</tr>
</tbody>

</table>
<h3 id="load-packages" class="anchored">Load Packages</h3>
<p>We use the following packages throughout the post:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing data</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Data analysis and wrangling</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization and styling</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<h3 id="data-sources" class="anchored">Data Sources</h3>
<p>We store Green Shield Canada’s source data in a transactional data model within an Oracle database. The purpose of the transaction model within Oracle is to quickly adjudicate medical claims within Green Shield’s Advantage application, and it has been performing exceptionally well. While a transactional data model provides great performance for transactional applications, the data model design is less than optimal for data analytics uses. Green Shield Canada, like many organizations, is undergoing a significant digital transformation with a high emphasis on data analytics. During the digital transformation, an analytical data model will be developed, built from many of the source tables currently stored in Oracle database tables, with the need to perform numerous data wrangling tasks.</p>
<p>Within Green Shield Canada, data is sized based on the following four groups:</p>
<ul>
<li>x-small dataset &lt; 1M rows (day)</li>
<li>small dataset 1-10M rows (month)</li>
<li>medium data 10-100M rows (year)</li>
<li>large data &gt; 100M-1B rows (decade)</li>
</ul>
<p>The main dataset used within the analysis is Green Shield Canada’s claim history data. This dataset includes various data elements related to the transactional claims submitted by Green Shield’s clients. This dataset is critically important to the organization, providing valuable insights into how the company operates and the service provided to our customers. The following is a table with the characteristics related to the claim history dataset.</p>
<div id="ktsbzxnuih" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>

</style>

<table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="6" class="gt_heading gt_title gt_font_normal" style="background-color: #005028; color: #FFFFFF; font-size: x-large; text-align: left; vertical-align: top; font-weight: bold; border-top-width: 3px; border-top-style: solid; border-top-color: #B6B6B6;">
Dataset Characteristics
</th>
</tr>
<tr>
<th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="background-color: #005028; color: #FFFFFF; font-size: small; text-align: left; vertical-align: top; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Claim History Data
</th>
</tr>
</thead>
<thead class="gt_col_headings">
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Dataset Size Group
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Dataset Name
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Number of Rows
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Number of Columns
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
CSV File Size
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Parquet File Size
</th>
</tr>
</thead>

<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
claim_history_day
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
317,617
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
201
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
281.8 MB
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
38.1 MB
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
claim_history_month
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
5,548,609
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
202
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
4.8 GB
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
711.9 MB
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
claim_history_year
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
66,001,292
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
201
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
57.3 GB
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
7.5 GB
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
claim_history
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
408,197,137
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
201
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
351.5 GB
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
45.1 GB
</td>
</tr>
</tbody>

</table>
</div>
<p>The second dataset used within the analysis is Green Shield Canada’s provider data. This dataset includes various data elements related to the provider network that provides medical services for Green Shield Canada’s customers. The following is a table with the characteristics associated with the provider dataset.</p>
<div id="pbnzuofvii" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>

</style>

<table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="5" class="gt_heading gt_title gt_font_normal" style="background-color: #005028; color: #FFFFFF; font-size: x-large; text-align: left; vertical-align: top; font-weight: bold; border-top-width: 3px; border-top-style: solid; border-top-color: #B6B6B6;">
Dataset Characteristics
</th>
</tr>
<tr>
<th colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="background-color: #005028; color: #FFFFFF; font-size: small; text-align: left; vertical-align: top; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Provider Data
</th>
</tr>
</thead>
<thead class="gt_col_headings">
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Dataset Name
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Number of Rows
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Number of Columns
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
CSV File Size
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Parquet File Size
</th>
</tr>
</thead>

<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
provider
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1,077,046
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
18
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
146.1 MB
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
31 MB
</td>
</tr>
</tbody>

</table>
</div>
<h2 id="the-solution" class="anchored">The Solution</h2>
<p>Green Shield Canada has decided to convert data sources used for analytics from row-based sources to a columnar format, specifically <a href="https://parquet.apache.org/" target="_blank">Apache Parquet</a>.</p>
<blockquote>
<p><em>Apache Parquet is an open source, column-oriented data file format designed for efficient data storage and retrieval. It provides efficient data compression and encoding schemes with enhanced performance to handle complex data in bulk.</em> <br> <em>— Apache Foundation</em></p>
</blockquote>
<p>We leverage the <a href="https://arrow.apache.org/docs/r/" target="_blank">arrow R package</a> to convert our row-based datasets into parquet files. Parquet partitions data into smaller chunks and enables improved performance when filtering against columns that have partitions.</p>
<p>Parquet file formats have three main benefits for analytical usage:</p>
<ul>
<li><strong>Compression</strong>: low storage consumption</li>
<li><strong>Speed</strong>: efficiently reads data in less time</li>
<li><strong>Interoperability</strong>: can be read by many different languages</li>
</ul>
<p>Converting our datasets from row-based (CSV) to columnar (parquet) has significantly reduced the file size. The CSV files range from <strong>4.7</strong> to <strong>7.8</strong> times larger than parquet files.</p>
<p>We will explore computationally expensive tasks in both data engineering and data analysis processes. We will perform four specific tasks on all four of the data sizes groups (x-small, small, medium, and large) produced from our claim history dataset.</p>
<ol type="1">
<li>join provider information to claim history</li>
<li>processed claims volume by benefit type per time interval (i.e., day, month, and/or year)</li>
<li>processed claims statistics by benefit type per time interval (i.e., day, month, and/or year)</li>
<li>provider information with processed claims statistics by benefit type per time interval (i.e., day, month, and/or year)</li>
</ol>
<h3 id="x-small-data" class="anchored">X-Small Data</h3>
<p>The x-small data consists of data collected on a single day in January 2021. The dataset has <strong>317,617</strong> rows of data.</p>
<h4 id="csv-data" class="anchored">CSV Data</h4>
<p>The CSV file used in this section was <strong>281.8 MB</strong> in size.</p>

<div id="tab" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 1_1', 'Task 1')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 1_2', 'Task 1')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 1_3', 'Task 1')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 1_4', 'Task 1')">Task 4</button></p>
</div>
<div id="Task 1_1" class="tabcontent" style="display:block;">
<pre><code># Task 1 - join
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_DAY.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id"))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>16.006 secs</strong> to execute.</p>
</div>
<div id="Task 1_2" class="tabcontent" style="none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

read_csv("/home/data/CLAIM_HISTORY_DAY.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>10.84989 secs</strong> to execute.</p>
</div>
<div id="Task 1_3" class="tabcontent">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

read_csv("/home/data/CLAIM_HISTORY_DAY.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>11.8559 secs</strong> to execute.</p>
</div>
<div id="Task 1_4" class="tabcontent">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_DAY.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description, BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>16.02928 secs</strong> to execute.</p>
</div>

<script>
function clickHandle(evt, tableNum, groupID) {
  let i, tabcontent, tablinks;

  // This is to clear the previous clicked content.
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    if (tabcontent[i].id.startsWith(groupID))
      tabcontent[i].style.display = "none";
  }

  // Set the tab to be "active".
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    if (tabcontent[i].id.startsWith(groupID)) 
      tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Display the clicked tab and set it to active.
  document.getElementById(tableNum).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

<h4 id="parquet-data" class="anchored">Parquet Data</h4>
<p>The parquet file used in this section was <strong>38.1 MB</strong> in size.</p>

<div id="tab2" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 2_1', 'Task 2')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 2_2', 'Task 2')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 2_3', 'Task 2')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 2_4', 'Task 2')">Task 4</button></p>
</div>
<div id="Task 2_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

left_join(
  open_dataset(source = "/home/data/CLAIM_HISTORY_DAY") %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, BNFT_TYPE_CD, CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id,
           provider_type,
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>1.776429 secs</strong> to execute.</p>
</div>
<div id="Task 2_2" class="tabcontent">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_DAY") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD) %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n)) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>0.7456837 secs</strong> to execute.</p>
</div>
<div id="Task 2_3" class="tabcontent">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_DAY") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD, CH_REND_AMT) %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>0.2979383 secs</strong> to execute.</p>
</div>
<div id="Task 2_4" class="tabcontent">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

left_join(
  open_dataset(source = "/home/data/CLAIM_HISTORY_DAY") %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, BNFT_TYPE_CD, CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id,
           provider_type,
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description, BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>1.359842 secs</strong> to execute.</p>
</div>

<h3 id="small-data" class="anchored">Small Data</h3>
<p>The small data consists of data collected in January 2021. The dataset has <strong>5,548,609</strong> rows of data.</p>
<h4 id="csv-data-1" class="anchored">CSV Data</h4>
<p>The CSV file used in this section was <strong>4.8 GB</strong> in size.</p>

<div id="tab3" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 3_1', 'Task 3')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 3_2', 'Task 3')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 3_3', 'Task 3')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 3_4', 'Task 3')">Task 4</button></p>
</div>
<div id="Task 3_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_MONTH.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id"))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>3.677011 mins</strong> to execute.</p>
</div>
<div id="Task 3_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_DAY = col_double())

read_csv("/home/data/CLAIM_HISTORY_MONTH.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_DAY) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>3.161771 mins</strong> to execute.</p>
</div>
<div id="Task 3_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_DAY = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

read_csv("/home/data/CLAIM_HISTORY_MONTH.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_DAY) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>3.095256 mins</strong> to execute.</p>
</div>
<div id="Task 3_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_DAY = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_MONTH.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description,
           BNFT_TYPE_CD,
           PROCESS_DAY) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>3.44803 mins</strong> to execute.</p>
</div>

<h4 id="parquet-data-1" class="anchored">Parquet Data</h4>
<p>The parquet file used in this section was <strong>711.9 MB</strong> in size.</p>

<div id="tab4" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 4_1', 'Task 4')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 4_2', 'Task 4')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 4_3', 'Task 4')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 4_4', 'Task 4')">Task 4</button></p>
</div>
<div id="Task 4_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_MONTH"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID,
           BNFT_TYPE_CD, 
           CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id, provider_type, benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>1.604066 secs</strong> to execute.</p>
</div>
<div id="Task 4_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_MONTH") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD) %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n)) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>0.3016093 secs</strong> to execute.</p>
</div>
<div id="Task 4_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_MONTH") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD, CH_REND_AMT, PROCESS_DAY) %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_DAY) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>0.5149045 secs</strong> to execute.</p>
</div>
<div id="Task 4_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_MONTH"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID,
           BNFT_TYPE_CD, 
           CH_REND_AMT, 
           PROCESS_DAY),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id, 
           provider_type,
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description,
           BNFT_TYPE_CD, 
           PROCESS_DAY) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>1.12566 secs</strong> to execute.</p>
</div>

<h3 id="medium-data" class="anchored">Medium Data</h3>
<p>The medium data consists of data collected over 2021. The dataset has <strong>66,001,292</strong> rows of data.</p>
<h4 id="csv-data-2" class="anchored">CSV Data</h4>
<p>The CSV file used in this section was <strong>57.3 GB</strong> in size.</p>

<div id="tab5" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 5_1', 'Task 5')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 5_2', 'Task 5')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 5_3', 'Task 5')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 5_4', 'Task 5')">Task 4</button></p>
</div>
<div id="Task 5_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;- 
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_YEAR.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id"))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>40.19741 mins</strong> to execute.</p>
</div>
<div id="Task 5_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_MONTH = col_double())

read_csv("/home/data/CLAIM_HISTORY_YEAR.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_MONTH) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>38.88081 mins</strong> to execute.</p>
</div>
<div id="Task 5_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_MONTH = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

read_csv("/home/data/CLAIM_HISTORY_YEAR.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_MONTH) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount =
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount =
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>37.73755 mins</strong> to execute.</p>
</div>
<div id="Task 5_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_MONTH = col_double())

provider_columns &lt;-
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_YEAR.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description,
           BNFT_TYPE_CD, 
           PROCESS_MONTH) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>40.0343 mins</strong> to execute.</p>
</div>

<h4 id="parquet-data-2" class="anchored">Parquet Data</h4>
<p>The parquet file used in this section was <strong>7.5 GB</strong> in size.</p>

<div id="tab6" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 6_1', 'Task 6')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 6_2', 'Task 6')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 6_3', 'Task 6')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 6_4', 'Task 6')">Task 4</button></p>
</div>
<div id="Task 6_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_YEAR"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, BNFT_TYPE_CD, CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id,
           provider_type, 
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>4.153103 secs</strong> to execute.</p>
</div>
<div id="Task 6_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_YEAR") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD, PROCESS_MONTH) %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_MONTH) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n)) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>0.844259 secs</strong> to execute.</p>
</div>
<div id="Task 6_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

open_dataset(source = "/home/data/CLAIM_HISTORY_YEAR") %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD, CH_REND_AMT, PROCESS_MONTH) %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_MONTH) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>1.010546 secs</strong> to execute.</p>
</div>
<div id="Task 6_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_YEAR"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, 
           BNFT_TYPE_CD,
           CH_REND_AMT, 
           PROCESS_MONTH),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id,
           provider_type, 
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description,
           BNFT_TYPE_CD, 
           PROCESS_MONTH) %&gt;%
  summarize(minimum_amount = 
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>3.062172 secs</strong> to execute.</p>
</div>

<h3 id="large-data" class="anchored">Large Data</h3>
<p>The large data consists of data collected between 2014 and 2022. The dataset has <strong>408,197,137</strong> rows of data.</p>
<h4 id="csv-data-3" class="anchored">CSV Data</h4>
The CSV file used in this section was <strong>351.5 GB</strong> in size.

<div id="tab7" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 7_1', 'Task 7')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 7_2', 'Task 7')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 7_3', 'Task 7')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 7_4', 'Task 7')">Task 4</button></p>
</div>
<div id="Task 7_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

claims_columns &lt;- 
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double())

provider_columns &lt;- 
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_DECADE.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
          col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id"))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task did not complete, producing <strong>Error: std::bad_alloc</strong>.</p>
</div>
<div id="Task 7_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()
claims_columns &lt;- 
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_YEAR = col_double(),
            PROCESS_MONTH = col_double())

read_csv("/home/data/CLAIM_HISTORY_DECADE.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_YEAR, PROCESS_MONTH) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n))
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task did not complete, producing <strong>Error: std::bad_alloc</strong>.</p>
</div>
<div id="Task 7_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_YEAR = col_double(),
            PROCESS_MONTH = col_double())

provider_columns &lt;- 
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

read_csv("/home/data/CLAIM_HISTORY_DECADE.csv",
         col_types = claims_columns) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  group_by(BNFT_TYPE_CD, PROCESS_YEAR, PROCESS_MONTH) %&gt;%
  summarize(minimum_amount = 
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task did not complete, producing <strong>Error: std::bad_alloc</strong>.</p>
</div>
<div id="Task 7_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

claims_columns &lt;-
  cols_only(CLAIM_STATUS_TYPE_CD = col_character(),
            CH_SUBM_PROVIDER_ID = col_double(),
            BNFT_TYPE_CD = col_character(),
            CH_REND_AMT = col_double(),
            PROCESS_YEAR = col_double(),
            PROCESS_MONTH = col_double())

provider_columns &lt;- 
  cols_only(provider_id = col_double(),
            provider_type = col_character(),
            benefit_description = col_character())

left_join(
  read_csv("/home/data/CLAIM_HISTORY_DECADE.csv",
           col_types = claims_columns) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC"),
  read_csv("/home/data/PROVIDER.csv",
           col_types = provider_columns),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description, 
           BNFT_TYPE_CD, 
           PROCESS_YEAR, 
           PROCESS_MONTH) %&gt;%
  summarize(minimum_amount = 
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task did not complete, producing <strong>Error: std::bad_alloc</strong>.</p>
</div>

<h4 id="parquet-data-3" class="anchored">Parquet Data</h4>
<p>The parquet file used in this section was <strong>45.1 GB</strong> in size.</p>

<div id="tab8" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 8_1', 'Task 8')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 8_2', 'Task 8')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 8_3', 'Task 8')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 8_4', 'Task 8')">Task 4</button></p>
</div>
<div id="Task 8_1" class="tabcontent" style="display:block">
<pre><code># Task 1 - join
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_DECADE"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, BNFT_TYPE_CD, CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id, 
           provider_type, 
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>16.42989 secs</strong> to execute.</p>
</div>
<div id="Task 8_2" class="tabcontent" style="display:none">
<pre><code># Task 2 - group_by + count
start &lt;- Sys.time()

open_dataset(
  source = "/home/data/CLAIM_HISTORY_DECADE"
) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD) %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  count() %&gt;%
  ungroup() %&gt;%
  arrange(desc(n)) %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>4.389257 secs</strong> to execute.</p>
</div>
<div id="Task 8_3" class="tabcontent" style="display:none">
<pre><code># Task 3 - group_by + summarize
start &lt;- Sys.time()

open_dataset(
  source = "/home/data/CLAIM_HISTORY_DECADE"
) %&gt;%
  filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
  select(BNFT_TYPE_CD, CH_REND_AMT) %&gt;%
  group_by(BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount = 
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>4.441824 secs</strong> to execute.</p>
</div>
<div id="Task 8_4" class="tabcontent" style="display:none">
<pre><code># Task 4 - join + group_by + summarize
start &lt;- Sys.time()

left_join(
  open_dataset(
    source = "/home/data/CLAIM_HISTORY_DECADE"
  ) %&gt;%
    filter(CLAIM_STATUS_TYPE_CD == "PC") %&gt;%
    select(CH_SUBM_PROVIDER_ID, BNFT_TYPE_CD, CH_REND_AMT),
  open_dataset(sources = "/home/data/Provider") %&gt;%
    select(provider_id,
           provider_type, 
           benefit_description),
  by = c("CH_SUBM_PROVIDER_ID" = "provider_id")) %&gt;%
  group_by(benefit_description, BNFT_TYPE_CD) %&gt;%
  summarize(minimum_amount =
              min(CH_REND_AMT, na.rm = TRUE),
            mean_amount = 
              mean(CH_REND_AMT, na.rm = TRUE),
            max_amount = 
              max(CH_REND_AMT, na.rm = TRUE)) %&gt;%
  ungroup() %&gt;%
  collect()
  
end &lt;- Sys.time()
end - start</code></pre>
<p>The task took <strong>14.93252 secs</strong> to execute.</p>
</div>

<h2 id="our-findings" class="anchored">Our Findings</h2>
<p>The results from our analysis were remarkable. Converting our data from row-based to columnar in parquet format significantly improved processing time. Processes that would take tens of minutes to an hour are now possible within seconds…<strong>game changer</strong>! The parquet format is a low/no-cost solution that provides immediate analytical improvements for both our data engineering and data analytics teams.</p>
<h3 id="processing-time" class="anchored">Processing Time</h3>
<p>CSV processing time varied from <strong>10.85</strong> seconds to <strong>2,411.84</strong> seconds (40.2 minutes), whereas parquet file processing time ranged from <strong>0.3</strong> seconds to <strong>16.43</strong> seconds for all four dataset size groups. Note that the CSV large dataset errored (<em>Error: std::bad_alloc</em>) and did not complete. The <em>Error: std::bad_alloc</em> is synonymous with out-of-memory, yes insufficient memory even with our 1TB workstation!</p>

<div id="tab9" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 9_1', 'Task 9')">Task 1</button> <button class="tablinks" onclick="clickHandle(event, 'Task 9_2', 'Task 9')">Task 2</button> <button class="tablinks" onclick="clickHandle(event, 'Task 9_3', 'Task 9')">Task 3</button> <button class="tablinks" onclick="clickHandle(event, 'Task 9_4', 'Task 9')">Task 4</button></p>
</div>
<div id="Task 9_1" class="tabcontent" style="display:block">
<p><img src="images/unnamed-chunk-39-1.png" class="img-fluid"></p>
</div>
<div id="Task 9_2" class="tabcontent" style="display:none">
<p><img src="images/unnamed-chunk-40-1.png" class="img-fluid"></p>
</div>
<div id="Task 9_3" class="tabcontent" style="display:none">
<p><img src="images/unnamed-chunk-41-1.png" class="img-fluid"></p>
</div>
<div id="Task 9_4" class="tabcontent" style="display:none">
<p><img src="images/unnamed-chunk-42-1.png" class="img-fluid"></p>
</div>

<h3 id="improvement-factor" class="anchored">Improvement Factor</h3>
<p>Not only did our processing efficiency improve across all categories of sizes of data, but storage size efficiency of the same datasets is also not to be overlooked. Being able to compute common analytical querying quicker and with a smaller footprint is an unrefutable win. Optimization in both size and speed is an attainable innovation for any Data Engineer/Analyst that is quantifiable and beneficial for any organization.</p>
<p>The following illustrates the improvement factor (aka the number of times improvement using parquet provides over CSV) for each of the four tasks, as well as the storage size improvements obtained using columnar storage.</p>

<div id="tab0" class="tab">
<p><button class="tablinks" onclick="clickHandle(event, 'Task 0_1', 'Task 0')">Processing Improvement</button> <button class="tablinks" onclick="clickHandle(event, 'Task 0_2', 'Task 0')">Improvement Distribution</button> <button class="tablinks" onclick="clickHandle(event, 'Task 0_3', 'Task 0')">Average Improvement</button> <button class="tablinks" onclick="clickHandle(event, 'Task 0_4', 'Task 0')">File Storage Improvement</button></p>
</div>
<div id="Task 0_1" class="tabcontent" style="display:block">
<div id="pfwhzcnkop" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="background-color: #005028; color: #FFFFFF; font-size: x-large; text-align: left; vertical-align: top; font-weight: bold; border-top-width: 3px; border-top-style: solid; border-top-color: #B6B6B6;">
Processing Improvements with Parquet Files
</th>
</tr>
</thead>
<thead class="gt_col_headings">
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Dataset Size Group
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Task
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
CSV Processing Time (in seconds)
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Parquet Processing Time (in seconds)
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Parquet Improvement Factor
</th>
</tr>
</thead>

<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
16.01
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1.78
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
9
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + count
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
10.85
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
0.75
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
15
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + summarize
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
11.86
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
0.30
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
40
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join + group_by + summarize
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
16.03
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1.36
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
12
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
220.62
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1.60
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
138
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + count
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
189.71
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
0.30
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
629
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + summarize
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
185.72
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
0.51
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
361
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join + group_by + summarize
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
206.88
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1.13
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
184
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,411.84
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
4.15
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
581
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + count
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,332.85
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
0.84
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,763
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + summarize
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,264.25
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1.01
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,241
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join + group_by + summarize
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
2,402.06
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
3.06
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
784
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
16.43
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + count
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
4.39
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
group_by + summarize
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
4.44
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_left" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
join + group_by + summarize
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
14.93
</td>
<td class="gt_row gt_right" style="background-color: #E4E4E5; color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
</tr>
</tbody>
<tfoot class="gt_sourcenotes">
<tr>
<td class="gt_sourcenote" style="background-color: #FFFFFF; color: #414042; font-size: x-small; text-align: left; vertical-align: middle;" colspan="5">
CSV large dataset did not complete <br> Producing Error: std::bad_alloc
</td>
</tr>
</tfoot>

</table>
</div>
</div>
<div id="Task 0_2" class="tabcontent" style="display:none">
<p><img src="images/unnamed-chunk-44-1.png" class="img-fluid"></p>
</div>
<div id="Task 0_3" class="tabcontent" style="display:none">
<div id="xqnbigurhc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="2" class="gt_heading gt_title gt_font_normal" style="background-color: #005028; color: #FFFFFF; font-size: x-large; text-align: left; vertical-align: top; font-weight: bold; border-top-width: 3px; border-top-style: solid; border-top-color: #B6B6B6;">
Average Processing Improvements with Parquet Files
</th>
</tr>
<tr>
<th colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="background-color: #005028; color: #FFFFFF; font-size: small; text-align: left; vertical-align: top; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
By Dataset Group Size
</th>
</tr>
</thead>
<thead class="gt_col_headings">
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Dataset Size Group
</th>
<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="background-color: #8DC63F; color: #414042; font-size: medium; text-align: center; vertical-align: middle; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
Average Parquet Improvement Factor
</th>
</tr>
</thead>

<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
x-small
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
19
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
small
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
328
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
medium
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
1,592
</td>
</tr>
<tr>
<td class="gt_row gt_left" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
large
</td>
<td class="gt_row gt_right" style="color: #414042; text-align: center; vertical-align: middle; white-space: pre; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #B6B6B6;">
NA
</td>
</tr>
</tbody>
<tfoot class="gt_sourcenotes">
<tr>
<td class="gt_sourcenote" style="background-color: #FFFFFF; color: #414042; font-size: x-small; text-align: left; vertical-align: middle;" colspan="2">
CSV large dataset did not complete <br> Producing Error: std::bad_alloc
</td>
</tr>
</tfoot>

</table>
</div>
</div>
<div id="Task 0_4" class="tabcontent" style="display:none">
<p><img src="images/unnamed-chunk-46-1.png" class="img-fluid"></p>
</div>

<h2 id="closing-remarks" class="anchored">Closing Remarks</h2>
<p>The time it takes to process data impacts all users, data engineers, data analytics, data scientists, decision makers, business users, and clients. Reducing processing time will improve the experience for all users along the data journey. Parquet files allow for analytical teams to reduce their analytical time significantly, be that data engineering, modelling, or data analytics. With parquet not requiring all the data to be read into memory prior to analysis, the file format provides an option for all organizations, regardless of their existing data infrastructure investment.</p>
<p>Analytics looks to provide value to business; many times it focuses on improving efficiencies of models or adding new technology. Sometimes we can get significant improvements that pay value to business with simple solutions, like changing data storage formats. Boring yes, but <strong>1,500</strong> times faster processing is super!</p>
<div class="lt-gray-box">
<p><b>Correction:</b> The original version of this post was missing <code>col_types</code> in <code>read_csv()</code>.</p>
</div>


<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>



</body></html>