<?php

include_once('core/wp-saml-auth.php');
include_once('core/sso-login.php');
include_once('core/disable-user-endpoint.php');
require_once('core/helpers.php');
require_once('core/tinymce-config.php');
require_once('core/theme-setup.php');
include_once('core/ajax-actions.php');
include_once('core/acf-configuration.php');
include_once('core/custom-post-types.php');
include_once('core/custom-routing.php');
include_once('core/hangouts-endpoints.php');
include_once('core/conferences.php');
include_once('core/resources.php');
include_once('importer/setup.php');
include_once('core/wp-mime-types.php');
include_once('core/cache-control.php');
include_once('core/admin-columns.php');
include_once('core/limitloginlogged.php');
include_once('core/add-headers.php');