name: Posit Deploy

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions: write-all
   
    steps:
      - uses: actions/checkout@v2
        name: build packages

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd wp-content/themes/Posit
          echo "npm install starts"
          npm install
          echo "npm install completed"
          npm run production        
       
       
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          version: 1
          args: --profile --ignore-platform-reqs
          working_dir: wp-content/themes/Posit/
         
         
      - name: Prepare Environment
        env:
          ENVIRONMENT_NAME: aw1275
          SSH_KEY_PRIVATE: ${{ secrets.PRIVATEPANTHEONKEYAW }}
          SSH_KEY_PUBLIC: ${{ secrets.PUBLICKEYAW }}
          LOCAL_BRANCH: develop
          SSH_PATH: /home/runner/.ssh
          HOST: ${{ secrets.PANTHEONHOST }}
          KNOWN_HOSTS_PATH: /home/runner/.ssh/known_hosts
          KNOWN_HOST_URL: ${{ secrets.KNOWN_HOST_URL }}
          SSH_CONFIG: /home/runner/.ssh/config
          SSH_KEY_PRIVATE_PATH: /home/runner/.ssh/id_rsa
          SSH_KEY_PUBLIC_PATH: /home/runner/.ssh/id_rsa.pub
          ENV: development
          LOCAL_BRANCH_DEFAULT: develop
          BRANCH: develop

        run: |
          mkdir -p $SSH_PATH
          echo starting environment configuration        
          echo "$KNOWN_HOST_URL" >> $SSH_CONFIG
          ssh-keyscan -t rsa codeserver.dev.a63ca213-cb1c-4c09-a68a-0ca1f9daf173.drush.in >> $KNOWN_HOSTS_PATH
          echo known_host file should be complete now:
          cat $KNOWN_HOSTS_PATH
          echo "$SSH_KEY_PRIVATE" > "$SSH_KEY_PRIVATE_PATH"
          echo "$SSH_KEY_PUBLIC" > "$SSH_KEY_PUBLIC_PATH"
          chmod 700 "$SSH_PATH"
          chmod 644 "$KNOWN_HOSTS_PATH"
          chmod 600 "$SSH_KEY_PRIVATE_PATH"
          chmod 644 "$SSH_KEY_PUBLIC_PATH"
          touch /home/runner/work/what.txt
          cat /home/runner/.ssh/config > "/home/runner/work/what.txt"
          cd ~/work/
          cat what.txt
          ls -la
          git clone ssh://codeserver.dev.a63ca213-cb1c-4c09-a68a-0ca1f9daf173@codeserver.dev.a63ca213-cb1c-4c09-a68a-0ca1f9daf173.drush.in:2222/~/repository.git awbuild
     
      - name: Push to Pantheon
        run: |

          rsync -avz --delete ~/work/posit-web/posit-web/wp-content/ ~/work/rstudiobuild/wp-content --exclude="/uploads/" --include="/themes/" --include="/themes/Posit/dist/"  --include="/plugins/" --exclude="/mu-plugins/" --exclude="/themes/posit-web/node_modules/"
          cd  ~/work/rstudiobuild/wp-content/themes/Posit
          echo '!dist'  >> .gitignore
          echo '!vendor' >> .gitignore
          echo '!dist/lottie' >> .gitignore
          cat .gitignore
          cd ~/work/rstudiobuild/wp-content/themes/Posit
          git status
          git config --global user.name "Github deployment"
          git config --global user.email "andrewwilliams1275@gmail.com"
          git add --all
          git commit -m "Build for Server"
          git push --force


